site_name: Webkom instruks
nav:
  - Kom i gang: 
    - Introduksjon: index.md
    - Installasjon av programvare: intro/program.md
    - Nedlasting av kode: intro/code.md
  - Opplæring: 
    - Introduksjon: kurs/intro.md
    - GDPR: kurs/GDPR.md
    - Terminal: kurs/terminal.md
  - Instruks:
    - Server: guides/server.md
  - Webkomiteen:
    - Om: webkom/about.md

theme: readthedocs

plugins:
  - include-markdown

extra_css:
  - assets/custom.css
extra_javascript:
  - assets/tabs.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3 
  - attr_list
  - md_in_html




  
