site_name: Webkom instruks
nav:
  - Kom i gang: index.md
  - Om: about.md

theme: readthedocs

plugins:
  - include-markdown

extra_css:
  - assets/custom.css
extra_javascript:
  - assets/tabs.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html




  
