site_name: Webkom instruks
nav:
  - Kom i gang: 
    - Introduksjon: index.md
    - Installasjon av programvare: program.md
    - Nedlasting av kode: code.md
  - Kurs: 
    - Terminal: index copy.md
  - Om: about.md

theme: readthedocs

plugins:
  - include-markdown

extra_css:
  - assets/custom.css
extra_javascript:
  - assets/tabs.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3 
  - attr_list
  - md_in_html




  
